/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Column } from "./shared/interfaces";
export namespace Components {
    interface FlinkeyDropdown {
        "defaultBtnText": string;
        "valuesForDropdown": Array<string | number | object>;
    }
    interface FlinkeyKeyfobCatalog {
    }
    interface FlinkeyModal {
        "body": string;
        "linkedServices": any;
        "modalTitle": string;
        "product": number;
        "service": number;
    }
    interface FlinkeyProductServiceTable {
        "isIdVisible": boolean;
        "isSapNumberVisible": boolean;
        "isSerialNumberVisible": boolean;
        "isUniqueIdVisible": boolean;
    }
    interface FlinkeyTable {
        "columns": Column[];
        "data": any[];
    }
}
declare global {
    interface HTMLFlinkeyDropdownElement extends Components.FlinkeyDropdown, HTMLStencilElement {
    }
    var HTMLFlinkeyDropdownElement: {
        prototype: HTMLFlinkeyDropdownElement;
        new (): HTMLFlinkeyDropdownElement;
    };
    interface HTMLFlinkeyKeyfobCatalogElement extends Components.FlinkeyKeyfobCatalog, HTMLStencilElement {
    }
    var HTMLFlinkeyKeyfobCatalogElement: {
        prototype: HTMLFlinkeyKeyfobCatalogElement;
        new (): HTMLFlinkeyKeyfobCatalogElement;
    };
    interface HTMLFlinkeyModalElement extends Components.FlinkeyModal, HTMLStencilElement {
    }
    var HTMLFlinkeyModalElement: {
        prototype: HTMLFlinkeyModalElement;
        new (): HTMLFlinkeyModalElement;
    };
    interface HTMLFlinkeyProductServiceTableElement extends Components.FlinkeyProductServiceTable, HTMLStencilElement {
    }
    var HTMLFlinkeyProductServiceTableElement: {
        prototype: HTMLFlinkeyProductServiceTableElement;
        new (): HTMLFlinkeyProductServiceTableElement;
    };
    interface HTMLFlinkeyTableElement extends Components.FlinkeyTable, HTMLStencilElement {
    }
    var HTMLFlinkeyTableElement: {
        prototype: HTMLFlinkeyTableElement;
        new (): HTMLFlinkeyTableElement;
    };
    interface HTMLElementTagNameMap {
        "flinkey-dropdown": HTMLFlinkeyDropdownElement;
        "flinkey-keyfob-catalog": HTMLFlinkeyKeyfobCatalogElement;
        "flinkey-modal": HTMLFlinkeyModalElement;
        "flinkey-product-service-table": HTMLFlinkeyProductServiceTableElement;
        "flinkey-table": HTMLFlinkeyTableElement;
    }
}
declare namespace LocalJSX {
    interface FlinkeyDropdown {
        "defaultBtnText"?: string;
        "onValueChanged"?: (event: CustomEvent<any>) => void;
        "valuesForDropdown"?: Array<string | number | object>;
    }
    interface FlinkeyKeyfobCatalog {
    }
    interface FlinkeyModal {
        "body"?: string;
        "linkedServices"?: any;
        "modalTitle"?: string;
        "onCloseModal"?: (event: CustomEvent<boolean>) => void;
        "onUpdateData"?: (event: CustomEvent<any>) => void;
        "product"?: number;
        "service"?: number;
    }
    interface FlinkeyProductServiceTable {
        "isIdVisible"?: boolean;
        "isSapNumberVisible"?: boolean;
        "isSerialNumberVisible"?: boolean;
        "isUniqueIdVisible"?: boolean;
    }
    interface FlinkeyTable {
        "columns"?: Column[];
        "data"?: any[];
    }
    interface IntrinsicElements {
        "flinkey-dropdown": FlinkeyDropdown;
        "flinkey-keyfob-catalog": FlinkeyKeyfobCatalog;
        "flinkey-modal": FlinkeyModal;
        "flinkey-product-service-table": FlinkeyProductServiceTable;
        "flinkey-table": FlinkeyTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flinkey-dropdown": LocalJSX.FlinkeyDropdown & JSXBase.HTMLAttributes<HTMLFlinkeyDropdownElement>;
            "flinkey-keyfob-catalog": LocalJSX.FlinkeyKeyfobCatalog & JSXBase.HTMLAttributes<HTMLFlinkeyKeyfobCatalogElement>;
            "flinkey-modal": LocalJSX.FlinkeyModal & JSXBase.HTMLAttributes<HTMLFlinkeyModalElement>;
            "flinkey-product-service-table": LocalJSX.FlinkeyProductServiceTable & JSXBase.HTMLAttributes<HTMLFlinkeyProductServiceTableElement>;
            "flinkey-table": LocalJSX.FlinkeyTable & JSXBase.HTMLAttributes<HTMLFlinkeyTableElement>;
        }
    }
}
