/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlinkeyKeyfobCatalog {
    }
}
declare global {
    interface HTMLFlinkeyKeyfobCatalogElement extends Components.FlinkeyKeyfobCatalog, HTMLStencilElement {
    }
    var HTMLFlinkeyKeyfobCatalogElement: {
        prototype: HTMLFlinkeyKeyfobCatalogElement;
        new (): HTMLFlinkeyKeyfobCatalogElement;
    };
    interface HTMLElementTagNameMap {
        "flinkey-keyfob-catalog": HTMLFlinkeyKeyfobCatalogElement;
    }
}
declare namespace LocalJSX {
    interface FlinkeyKeyfobCatalog {
    }
    interface IntrinsicElements {
        "flinkey-keyfob-catalog": FlinkeyKeyfobCatalog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flinkey-keyfob-catalog": LocalJSX.FlinkeyKeyfobCatalog & JSXBase.HTMLAttributes<HTMLFlinkeyKeyfobCatalogElement>;
        }
    }
}
