name: Build & Publish Package

on:
  push:
    branches:
      - master
      - feature/1-setup-github-actions-pipeline-to-build-and-publish-package-to-npm

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./components
        run: |
          npm i
      - name: Check code style (Prettier)
        working-directory: ./components
        run: |
          npm run format:check
      - name: Run Unit Tests
        working-directory: ./components
        run: |
          npm run test:unit
      - name: Run E2E Tests
        working-directory: ./components
        run: |
          npm run test:e2e
      - name: Build components
        working-directory: ./components
        run: |
          npm run build
      - name: Remove node_modules
        working-directory: ./components
        run: |
          rm -rf node_modules/
      - name: Upload artifact
        working-directory: ./components
        uses: actions/upload-artifact@v2.2.2
        with:
          name: flinkey_web_components_artifact
          path: components
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Download artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: flinkey_web_components_artifact
      - name: Publish package on NPM
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}