name: Build & Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./components
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i
      - name: Check code style (Prettier)
        run: |
          npm run format:check
      - name: Run Unit Tests
        run: |
          npm run test:unit
      - name: Run E2E Tests
        run: |
          npm run test:e2e
      - name: Build components
        run: |
          npm run build
      - name: Copy README
        run: |
          cp ../README.md README.md
      - name: Copy LICENSE
        run: |
          cp ../LICENSE LICENSE
      - name: Remove node_modules
        run: |
          rm -rf node_modules/
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: flinkey_web_components_artifact
          path: components

  pre_publish_validation:
    name: Pre-Publish Validation
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version_increased: ${{ steps.check_package_version.outputs.version_increased }}
      package_version: ${{ steps.check_package_version.outputs.package_version }}

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: flinkey_web_components_artifact

      - name: Read PR versions
        if: ${{ env.skipVersionValidation == 'False' }}
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/scripts/read_versions.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/scripts/read_versions.sh"

      - name: Check PR package version
        if: ${{ env.skipVersionValidation == 'False' }}
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          PACKAGE_LOCK_VERSION: ${{ env.PACKAGE_LOCK_VERSION }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/scripts/validate_versions.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/scripts/validate_versions.sh"

      - name: Check for package version update
        id: check_package_version
        run: |
          echo "Local package version: ${{ env.PACKAGE_VERSION }}"
          npmPackageVersion=$( npm show @planbgmbh/flinkey-web-components version )
          echo "Latest package version on NPM: $npmPackageVersion"
          if $(dpkg --compare-versions ${{ env.PACKAGE_VERSION }} gt $npmPackageVersion);
          then
            echo '::set-output name=version_increased::True'
            echo 'Version updated'
          else
            echo '::set-output name=version_increased::False'
            echo 'Version did not update'
          fi
          echo '::set-output name=package_version::${{ env.PACKAGE_VERSION }}'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: pre_publish_validation
    if: ${{ needs.pre_publish_validation.outputs.version_increased == 'True' }}
    environment: NPM
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: flinkey_web_components_artifact

      - name: Prepare GitHub release
        run: |
          echo "packageVersion=${{ needs.pre_publish_validation.outputs.package_version }}" >> $GITHUB_ENV
          zipName="flinkey-web-components-v${packageVersion}.zip"
          echo "zipName=$zipName" >> $GITHUB_ENV
          changelog=$(<CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm CHANGELOG.md

      - name: Publish package on NPM
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub release artifact
        run: |
          wget --quiet --method GET -O npmPackageData.json "http://registry.npmjs.org/@planbgmbh/flinkey-web-components/${{ env.packageVersion }}"
          tarballUrl=$( jq -r '.dist.tarball' npmPackageData.json )
          wget --quiet --method GET -O npmPackage.tgz "$tarballUrl"
          mkdir unpackedPackage
          tar -zxvf ./npmPackage.tgz -C ./unpackedPackage
          cd ./unpackedPackage/package
          zip -r "../../${{ env.zipName }}" *

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.zipName }}
          body: ${{ env.changelog }}
          name: ${{ env.packageVersion }}
          tag: "v${{ env.packageVersion }}"
          token: ${{ secrets.GITHUB_TOKEN }}
