name: Run PR Checks

on: 
  [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: 'main'
          path: main
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          path: pr
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Read PR package version
        run: |
          cd ./pr/components
          prPackageVersion=$( jq -r '.version' package.json )
          echo "prPackageVersion=$prPackageVersion" >> $GITHUB_ENV
          echo "Current PR version: $prPackageVersion"
      - name: Read PR package-lock version
        run: |
          cd ./pr/components
          prPackageLockVersion=$( jq -r '.version' package-lock.json )
          echo "prPackageLockVersion=$prPackageLockVersion" >> $GITHUB_ENV
          echo "Current PR lock version: $prPackageLockVersion"
      - name: Check PR package version
        run: |
          echo "PR lock version ${{ env.prPackageLockVersion }}"
          echo "PR version ${{ env.prPackageVersion }}"
          if $(dpkg --compare-versions ${{ env.prPackageVersion }} eq ${{ env.prPackageLockVersion }});
          then
            echo 'PR package lock version and PR package version are equal'
          else
            echo 'PR package lock version and PR package version are not equal'
            exit 1
          fi
      - name: Check package version update
        run: |
          ./.github/workflows/check_package_version_update.sh
      - name: Install dependencies
        run: |
          cd ./pr/components
          npm i
      - name: Check code style (Prettier)
        run: |
          cd ./pr/components
          npm run format:check
      - name: Run Unit Tests
        run: |
          cd ./pr/components
          npm run test:unit
      - name: Run E2E Tests
        run: |
          cd ./pr/components
          npm run test:e2e
      - name: Build components
        run: |
          cd ./pr/components
          npm run build