name: Run PR Checks

on: 
  [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: 'main'
          path: main
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          path: pr
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Read PR package version
        run: |
          cd ./pr/components
          prPackageVersion=$( jq -r '.version' package.json )
          echo "prPackageVersion=$prPackageVersion" >> $GITHUB_ENV
          echo "Current PR version: $prPackageVersion"
      - name: Read PR package-lock version
        run: |
          cd ./pr/components
          prPackageLockVersion=$( jq -r '.version' package-lock.json )
          echo "prPackageLockVersion=$prPackageLockVersion" >> $GITHUB_ENV
          echo "Current PR lock version: $prPackageLockVersion"
      - name: Check PR package version
        run: |
          echo "PR lock version ${{ env.prPackageLockVersion }}"
          echo "PR version ${{ env.prPackageVersion }}"
          if $(dpkg --compare-versions ${{ env.prPackageVersion }} eq ${{ env.prPackageLockVersion }});
          then
            echo 'PR package lock version and PR package version are equal'
          else
            echo 'PR package lock version and PR package version are not equal'
            exit 1
          fi
      - name: Read main package version
        run: |
          cd ./main/components
          mainPackageVersion=$( jq -r '.version' package.json )
          echo "mainPackageVersion=$mainPackageVersion" >> $GITHUB_ENV
          echo "Current main version: $mainPackageVersion"
      - name: Check package version update
        run: |
          jq '.version = "null"' ./pr/components/package.json
          jq '.version = "null"' ./pr/components/package-lock.json
          jq '.version = "null"' ./main/components/package.json
          jq '.version = "null"' ./main/components/package-lock.json
          diff -qr pr/components main/components && changes=0 || changes=1
          jq '.version = "${{ env.prPackageVersion }}"' ./pr/components/package.json
          jq '.version = "${{ env.prPackageLockVersion }}"' ./pr/components/package-lock.json
          if [ $changes -eq 1 ];
          then
            echo 'components directory content changed'
            echo "PR package version: ${{ env.prPackageVersion }}"
            echo "Latest package version on main: ${{ env.mainPackageVersion }}"
            if $(dpkg --compare-versions ${{ env.prPackageVersion }} gt ${{ env.mainPackageVersion }});
            then
              echo 'Version updated'
            else
              echo 'Version did not update'
              exit 1
            fi
          else
            echo 'components directory content did not change'
            if $(dpkg --compare-versions ${{ env.prPackageVersion }} neq ${{ env.mainPackageVersion }});
            then
              echo 'Version changed but should not'
              exit 1
            else
              echo 'Version did not change'
            fi
          fi
      - name: Install dependencies
        run: |
          cd ./pr/components
          npm i
      - name: Check code style (Prettier)
        run: |
          cd ./pr/components
          npm run format:check
      - name: Run Unit Tests
        run: |
          cd ./pr/components
          npm run test:unit
      - name: Run E2E Tests
        run: |
          cd ./pr/components
          npm run test:e2e
      - name: Build components
        run: |
          cd ./pr/components
          npm run build