name: Run PR Checks

on: [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.4.0
        with:
          ref: "main"
          path: main

      - name: Checkout PR branch
        uses: actions/checkout@v2.4.0
        with:
          path: pr

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check commit authors
        shell: bash
        env:
          USER_NAME: "${{ github.event.pull_request.user.login }}"
          LINK: "${{ github.event.pull_request._links.commits.href }}"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/author_validation.sh"
          "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/author_validation.sh"

      - name: Read PR versions
        if: ${{ env.skipVersionValidation == 'False' }}
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}/pr/"
          chmod +x "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/read_versions.sh"
          "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/read_versions.sh"

      - name: Check PR package version
        if: ${{ env.skipVersionValidation == 'False' }}
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          PACKAGE_LOCK_VERSION: ${{ env.PACKAGE_LOCK_VERSION }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/validate_versions.sh"
          "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/validate_versions.sh"

      - name: Check package version update
        if: ${{ env.skipVersionValidation == 'False' }}
        env:
          PR_PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/pr_check_version_update.sh"
          "${GITHUB_WORKSPACE}/pr/.github/workflows/scripts/pr_check_version_update.sh"

      - name: Install dependencies
        run: |
          cd ./pr/components
          npm i

      - name: Check code style (Prettier)
        run: |
          cd ./pr/components
          npm run format:check

      - name: Run Unit Tests
        run: |
          cd ./pr/components
          npm run test:unit

      - name: Run E2E Tests
        run: |
          cd ./pr/components
          npm run test:e2e

      - name: Build components
        run: |
          cd ./pr/components
          npm run build
