name: Run PR Checks

on: ["pull_request"]

defaults:
  run:
    working-directory: ./components

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i
      - name: Check code style (Prettier)
        run: |
          npm run format:check
      - name: Run Unit Tests
        run: |
          npm run test:unit
      - name: Run E2E Tests
        run: |
          npm run test:e2e
      - name: Build components
        run: |
          npm run build
